name: Publish to github packages
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
            - uses: jetli/wasm-pack-action@v0.4.0
            - uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  registry-url: "https://npm.pkg.github.com"
            - uses: pnpm/action-setup@v3
              with:
                  version: 8
            - run: pnpm ci
            - run: pnpm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
