name: Publish to github packages
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
            - uses: jetli/wasm-pack-action@v0.4.0
            - uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  registry-url: https://npm.pkg.github.com
            - uses: pnpm/action-setup@v3
              with:
                  version: 8
            - run: ./build.sh
            - run: echo @elimerl:registry=https://npm.pkg.github.com > ~/.npmrc
            - run: pnpm config set '//npm.pkg.github.com/:_authToken' "${NODE_AUTH_TOKEN}"
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - run: pnpm install --frozen-lockfile
              working-directory: pkg
            - run: echo "TARBALL=$(pnpm pack)" >> $GITHUB_ENV
              working-directory: pkg
            - uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: "${{ env.TARBALL }}"
